### ISSUE TITLE
Synchronous root_dir setting contributes to suboptimal load times

### ISSUE THREAD

**Issue by gregorias** [nvimtools/none-ls.nvim#11]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Implement support for asynchronous [`root_dir` setting](https://github.com/nvimtools/none-ls.nvim/blob/dc9b7e28f5573a1a2225ffb33893d23d3e052ed6/lua/null-ls/config.lua#L19).

Right now, it uses synchronous [`root_pattern`](https://github.com/nvimtools/none-ls.nvim/blob/dc9b7e28f5573a1a2225ffb33893d23d3e052ed6/lua/null-ls/utils/init.lua#L254) and [gets executed on `FileType` events](https://github.com/nvimtools/none-ls.nvim/blob/dc9b7e28f5573a1a2225ffb33893d23d3e052ed6/lua/null-ls/client.lua#L76). Since `root_pattern` uses blocking FS operations, this can add noticable time delays to startup time. It does so on my NFS system, where I need to wait 2-5s during initial start up.

### Help

Yes

### Implementation help

Guidelines on what kind of interface or breaking changes you would be fine with in order to get it done.

**Comment by mochaaP** [comment]
Have been busy recently, someone feel free to take the job, thanks! :)

**Comment by gregorias** [comment]
I intend to take a look.
