### ISSUE TITLE
Setup in readme return an error with eslint

### ISSUE THREAD

**Issue by Its-Alex** [nvimtools/none-ls.nvim#110]
### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Hi,

I'm new to neovim ecosystem, when following the readme to install `none.ls` in the [Setup section](https://github.com/nvimtools/none-ls.nvim?tab=readme-ov-file#setup) I found a bug, when adding the following lines to my configuration:

```lua
        'nvimtools/none-ls.nvim',
        dependencies = {
            'nvim-lua/plenary.nvim',
        },
        config = function()
            local null_ls = require("null-ls")
            
            null_ls.setup({
                sources = {
                    null_ls.builtins.formatting.stylua,
                    null_ls.builtins.diagnostics.eslint,
                    null_ls.builtins.completion.spell,
                },
            })
        end
```

I have an error:

```
[null-ls] failed to load builtin eslint for method diagnostics; please check your config
```

Finding https://github.com/nvimtools/none-ls.nvim/discussions/81, I think that is because `eslint` has been moved to [none-ls-extras.nvim](https://github.com/nvimtools/none-ls-extras.nvim) because this is working:

```lua
        'nvimtools/none-ls.nvim',
        dependencies = {
            'nvim-lua/plenary.nvim',
            "nvimtools/none-ls-extras.nvim",
        },
        config = function()
            local null_ls = require("null-ls")
            
            null_ls.setup({
                sources = {
                    null_ls.builtins.formatting.stylua,
                    require("none-ls.diagnostics.eslint"),
                    null_ls.builtins.completion.spell,
                },
            })
        end
```

Can you please fix the readme if I'm right and add section about [none-ls-extras.nvim](https://github.com/nvimtools/none-ls-extras.nvim)? I can submit a PR if you want :slightly_smiling_face:  

If I'm in the wrong can you explain me why? I can't find any answers.

Thanks in advance!

### Help

Yes

**Comment by mochaaP** [comment]
Thanks for the catch! This is now fixed in f44485f :)
