### ISSUE TITLE
`reformat-gherkin` support

### ISSUE THREAD

**Issue by Zeioth** [nvimtools/none-ls.nvim#122]
### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

none-ls doesn't load the next formatter: https://github.com/ducminh-phan/reformat-gherkin

* You can install the formatter using mason, filtering by "cucumber".
* You can find .feature files to test the formatter [here](https://github.com/ducminh-phan/reformat-gherkin/tree/master/tests/gherkin_test_data).

### Help

Yes, but I don't know how to start. I would need guidance

**Comment by Zeioth** [comment]
PR here: https://github.com/nvimtools/none-ls.nvim/pull/123

**Comment by mochaaP** [comment]
Merged in none-ls-extras: <https://github.com/nvimtools/none-ls-extras.nvim/commit/336e84b9e43c0effb735b08798ffac382920053b>

**Comment by Zeioth** [comment]
@mochaaP What we add to none-ls-extras is not gonna work correctly (see https://github.com/nvimtools/none-ls.nvim/issues/90)

For example in the next image, reformat-cucumber is not installed, but because it is present in `sources = {}`, it will be reported as available.
![screenshot_2024-05-10_18-49-50_149890376](https://github.com/nvimtools/none-ls.nvim/assets/3357792/891c596d-55b7-4a4d-9bc7-cddf95c4f560)

Causing an error when you try to format.
![screenshot_2024-05-10_18-51-58_029003400](https://github.com/nvimtools/none-ls.nvim/assets/3357792/6756f1dd-cbed-4711-bd0c-7f7fbf838acc)

**Comment by Zeioth** [comment]
Apart from that, this formatter is not legacy, nor have any other alternative supported in none-ls. It should not be in extra.
