### ISSUE TITLE
`eslint_d` diagnostics not shown when buffer is opened.

### ISSUE THREAD

**Issue by magnusriga** [nvimtools/none-ls.nvim#207]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.11.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Run "nvim -V1 -v" for more info

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

WSL 2

### Minimal Config

```Lua
n/a
```

### Steps to Reproduce

1. Open nvim and shut down `eslint_d`: `:! eslint_d stop`.
2. Reopen nvim and navigate to a file which has eslint errors.
3. Observe that diagnostics do not show.
4. Restart nvim.
5. Navigate to the same file and observe that the diagnostics now show.

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

I expected the diagnostics from `eslint_d` to show after opening, i.e. entering, the buffer.

### Actual Behavior

Instead, diagnostics are not shown until a change has been made to the buffer.

There is some kind of order issue here, as restarting nvim after `null-ls` has run once, fixes the issue.

I first thought it had to do with the `eslint_d` deamon not being started, but manually starting it with `:! estlnt_d start`, prior to opening a buffer, does not fix the problem.

### Debug Log

n/a

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by magnusriga** [comment]
Actually, it seems manually starting `eslint_d` before opening the buffer does not fix the issue. Steps to reproduce:

1. Open nvim and shut down `eslint_d`: `:! eslint_d stop`.
2. Reopen eslint and navigate to a file which has eslint errors.
3. Observe that diagnostics do not show.
4. Restart nvim.
5. Navigate to the same file and observe that the diagnostics now show.

**Comment by mochaaP** [comment]
strictly speaking, this should be an eslint_d design limitation (iirc). could you try replicating this with eslint-lsp?

**Comment by felipe-heredia** [comment]
@magnusriga I had the same problem.

https://github.com/GR3YH4TT3R93/OurNvim.lazy/pull/1

May be this would help you.

**Comment by magnusriga** [comment]
@felipe-heredia Thanks for chiming in, but I am already using `none-ls-extras` and `none-ls`. It works after an edit has been made, but not when buffer is opened.

**Comment by mochaaP** [comment]
the `_d` tools are, to my knowledge, not faster than a properly warmed up js vm (e.g. with v8 heap snapshot blobs) or any similar tools that persist in the memory (eslint_lsp in this case) by a significant margin.

please try eslint_lsp and give your feedback, it should be snappier, if not the same, as eslint_d.
