### ISSUE TITLE
rpc: attempt to concat local 'method' (a table value)

### ISSUE THREAD

**Issue by name-jerry** [nvimtools/none-ls.nvim#213]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.11.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Run "nvim -V1 -v" for more info

### Dev Version?

- [ ] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

WSL 版本： 2.3.26.0 内核版本： 5.15.167.4-1 WSLg 版本： 1.0.65 MSRDC 版本： 1.2.5620 Direct3D 版本： 1.611.1-81528511 DXCore 版本： 10.0.26100.1-240331-1435.ge-release Windows 版本： 10.0.26100.2454

### Minimal Config

```Lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
  spec = {
    -- add your plugins here
    {
  "nvimtools/none-ls.nvim",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    "nvim-lua/plenary.nvim",
  },
  config = function()
    local null_ls = require("null-ls")
      null_ls.setup({
      sources = {
               null_ls.builtins.formatting.stylua,
      },
    })
  end,
}

  },
  -- Configure any other settings here. See the documentation for more details.
  -- colorscheme that will be used when installing plugins.
  install = { colorscheme = { "habamax" } },
  -- automatically check for plugin updates
  checker = { enabled = true },
})
```

### Steps to Reproduce

Type some letters in Insert mode and leave insert mode in the lua file

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

No error is reported when leaving insert mode

### Actual Behavior

error is reported when leaving insert mode

### Debug Log

[WARN  Tue Oct 22 08:52:06 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command prettier is not executable (make sure it's installed and on your $PATH)
[WARN  Mon Nov  4 16:53:12 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Tue Nov  5 11:29:58 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:09:07 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:12:41 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:19:11 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:23:47 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:25:49 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:27:15 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)
[WARN  Wed Nov  6 09:34:02 2024] /home/zr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:148: failed to run generator: ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/loop.lua:165: command stylua is not executable (make sure it's installed and on your $PATH)

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by name-jerry** [comment]
![Uploading img_v3_02h6_eef67e85-abab-4de4-ab18-edf0f1efd16g.jpg…]()

**Comment by Ask-786** [comment]
upvote ⬆️

**Comment by Ryntak94** [comment]
> Update neovim to the latest nightly, or use a stable release.
> 
> 不是很能理解你这里的问题在哪，如果你在用 neovim nightly 的话请更新到最新的 commit，详见 #209

I'm using nightly, currently getting this same error.
![image](https://github.com/user-attachments/assets/9316ec69-98a3-4998-9fd6-9c60dbac6c61)

**Comment by name-jerry** [comment]
> > Update neovim to the latest nightly, or use a stable release.
> > 不是很能理解你这里的问题在哪，如果你在用 neovim nightly 的话请更新到最新的 commit，详见 #209
> 
> I'm using nightly, currently getting this same error. ![image](https://private-user-images.githubusercontent.com/25399037/391697110-9316ec69-98a3-4998-9fd6-9c60dbac6c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODgyMDksIm5iZiI6MTczMzE4NzkwOSwicGF0aCI6Ii8yNTM5OTAzNy8zOTE2OTcxMTAtOTMxNmVjNjktOThhMy00OTk4LTlmZDYtOWM2MGRiYWM2YzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAxMDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjdhMjMxYWZkMmE1N2RkMmY0M2MxMzY3ZWI0ZmU5MDA1MDFjZjJiY2MxMTcyNDFhNWI0YWQ1ZTM0MWIyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cbDvrSt4Icet1VtTTKCg67lkY49ae670O683rHe1aoU)

bug会在commit：56e6e1b出现

**Comment by name-jerry** [comment]
> > Update neovim to the latest nightly, or use a stable release.
> > 不是很能理解你这里的问题在哪，如果你在用 neovim nightly 的话请更新到最新的 commit，详见 #209
> 
> I'm using nightly, currently getting this same error. ![image](https://private-user-images.githubusercontent.com/25399037/391697110-9316ec69-98a3-4998-9fd6-9c60dbac6c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODgyMDksIm5iZiI6MTczMzE4NzkwOSwicGF0aCI6Ii8yNTM5OTAzNy8zOTE2OTcxMTAtOTMxNmVjNjktOThhMy00OTk4LTlmZDYtOWM2MGRiYWM2YzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAxMDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjdhMjMxYWZkMmE1N2RkMmY0M2MxMzY3ZWI0ZmU5MDA1MDFjZjJiY2MxMTcyNDFhNWI0YWQ1ZTM0MWIyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cbDvrSt4Icet1VtTTKCg67lkY49ae670O683rHe1aoU)

bug在commit：56e6e1b后出现

**Comment by mochaaP** [comment]
I'm unable to reproduce this (`NVIM v0.11.0-dev-1265+g6cdcac4492` from <https://github.com/neovim/neovim/releases/nightly>):

```lua
vim.g.loaded_remote_plugins = ""
vim.o.runtimepath = vim.env["VIMRUNTIME"]

local temp_dir = vim.fs.dirname(vim.fs.dirname(vim.fn.tempname()))

local package_root = vim.fs.joinpath(temp_dir, "nvim", "site")
vim.o.packpath = package_root

local install_path = vim.fs.joinpath(package_root, "pack", "deps", "start", "mini.deps")

local null_ls_config = function()
	local null_ls = require("null-ls")
	-- add only what you need to reproduce your issue
	null_ls.setup({
		sources = {
			null_ls.builtins.formatting.stylua,
		},
		debug = true,
	})
end

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	local deps = require("mini.deps")
	deps.setup({
		path = {
			package = package_root,
		},
	})
	deps.add({
		source = "nvimtools/none-ls.nvim",
		depends = { "nvim-lua/plenary.nvim" },
	})
	deps.later(null_ls_config)
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/echasnovski/mini.deps", install_path })
end
load_plugins()

vim.treesitter.start = function() end
```

**Comment by mochaaP** [comment]
reopening for troubleshooting

**Comment by name-jerry** [comment]
> I'm unable to reproduce this (`NVIM v0.11.0-dev-1265+g6cdcac4492` from https://github.com/neovim/neovim/releases/nightly):
> 
> ```lua
> vim.g.loaded_remote_plugins = ""
> vim.o.runtimepath = vim.env["VIMRUNTIME"]
> 
> local temp_dir = vim.fs.dirname(vim.fs.dirname(vim.fn.tempname()))
> 
> local package_root = vim.fs.joinpath(temp_dir, "nvim", "site")
> vim.o.packpath = package_root
> 
> local install_path = vim.fs.joinpath(package_root, "pack", "deps", "start", "mini.deps")
> 
> local null_ls_config = function()
> 	local null_ls = require("null-ls")
> 	-- add only what you need to reproduce your issue
> 	null_ls.setup({
> 		sources = {
> 			null_ls.builtins.formatting.stylua,
> 		},
> 		debug = true,
> 	})
> end
> 
> local function load_plugins()
> 	-- only add other plugins if they are necessary to reproduce the issue
> 	local deps = require("mini.deps")
> 	deps.setup({
> 		path = {
> 			package = package_root,
> 		},
> 	})
> 	deps.add({
> 		source = "nvimtools/none-ls.nvim",
> 		depends = { "nvim-lua/plenary.nvim" },
> 	})
> 	deps.later(null_ls_config)
> end
> 
> if vim.fn.isdirectory(install_path) == 0 then
> 	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/echasnovski/mini.deps", install_path })
> end
> load_plugins()
> 
> vim.treesitter.start = function() end
> ```

谢谢，更新到NVIM v0.11.0-dev-1265+g6cdcac4492就不会有问题了
