### ISSUE TITLE
LSP: Proper LSP Capability detection

### ISSUE THREAD

**Issue by barrett-ruth** [nvimtools/none-ls.nvim#217]
### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Inherited code from null-ls detects client capabilities in [methods.lua](https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/methods.lua) with its own hard-coded values.

Recently, `vim.lsp.protocol.Methods` came in as a sort of "official" way to identify LSP capabilities. However, `none-ls` sources don't  really work with this - the following code returns false:

```lua
vim.print(client:supports_method('textDocument/formatting'))
vim.print(client:supports_method('formatting'))
vim.print(client:supports_method(vim.lsp.protocol.Methods['textDocument_formatting'])
```

I'm not sure where to find the *official* actual standardized rules as to what valid keys are - but `clangd` and `pylsp` and `lua_ls` all return `true` while `null-ls` sources return `false`.

### Help

Yes

### Implementation help

Ready to help!

**Comment by jfly** [comment]
@barrett-ruth, any luck with this? I should have some time next week to look into this if it would be helpful. Just don't want to duplicate effort :)

**Comment by barrett-ruth** [comment]
@jfly I'm going to look into this today. I'm not really sure where the actual specification for this stuff is... I was planning to use this issue as an opportunity to learn the LSP but if you have greater insight then I think you should just take over

**Comment by barrett-ruth** [comment]
related #209

**Comment by barrett-ruth** [comment]
To be honest, I have no idea what's happening here. On Arch Linux, `nvim == 0.10.3`, the `client:supports_method` syntax *is* supported if I force `none-ls` to use it. However, `none-ls` says this is only for `0.11` - using the `.`syntax works just fine. No idea why that is, TBH.

Closing because it's a non-issue - or at least mine is.

**Comment by jfly** [comment]
@barrett-ruth, I dug into this and figured out what was going wonky for me. Not sure if you're running into a variant of the same thing: https://github.com/nvimtools/none-ls.nvim/pull/231
