### ISSUE TITLE
Feature request: compute `dynamic_command` immediately when a buffer is opened

### ISSUE THREAD

**Issue by jfly** [nvimtools/none-ls.nvim#218]
### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

(I'm splitting this out from https://github.com/nvimtools/none-ls.nvim/issues/193)

https://github.com/nvimtools/none-ls.nvim/pull/197 just landed, which makes `dynamic_command` async. However, we don't start computing that `dynamic_command` until someone tries to actually format, which can take a while.

Since I usually spend some time reading a file before making a change, I expect this to make the `dynamic_command` delay disappear in practice (by the time I make a change and try to format my buffer, we'll have already computed the `dynamic_command`.

### Help

Yes

**Comment by mochaaP** [comment]
done in #220
