### ISSUE TITLE
Add line ranges to black for python

### ISSUE THREAD

**Issue by SamuilDichev** [nvimtools/none-ls.nvim#31]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

Black has recently been updated to allow for line ranges instead of just whole files ( [see their docs](https://github.com/psf/black/blob/main/docs/usage_and_configuration/the_basics.md#--line-ranges) )

`none-ls` should implement passing the `--line-ranges` argument and also allow black to be called for range formatting (add range formatting to methods)

### Help

Yes

**Comment by mochaaP** [comment]
Closed by #32
