### ISSUE TITLE
Conditionally apply extra_args if config not found

### ISSUE THREAD

**Issue by kaiphat** [nvimtools/none-ls.nvim#48]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I want to apply extra_args only if config for prettier doesn't exist.

### Help

No

**Comment by barrett-ruth** [comment]
Configure the source per-project. Anyways, this sounds like an [xy problem](https://www.wikiwand.com/en/articles/XY_problem), so please provide more background context to your issues in the future.
