### ISSUE TITLE
Jenkinsfile filetype doesn't work

### ISSUE THREAD

**Issue by MarcSeebold** [nvimtools/none-ls.nvim#5]
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.9.2

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Ubuntu 20.04 x64

### Minimal Config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
	local null_ls = require("null-ls")
	-- add only what you need to reproduce your issue
	null_ls.setup({
		sources = { null_ls.builtins.diagnostics.npm_groovy_lint, null_ls.builtins.formatting.npm_groovy_lint },
		debug = true,
	})
end

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"jose-elias-alvarez/null-ls.nvim",
				requires = { "nvim-lua/plenary.nvim" },
				config = null_ls_config,
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
else
	load_plugins()
	require("packer").sync()
end
```

### Steps to Reproduce

1. `nvim --clean -u minimal_init.lua Jenkinsfile`.
2. Close packer with "q" key.
3. Type ":NullLsInfo", return key

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

Supported source(s) should list "formatting: npm_groovy_lint" and "diagnostics: npm_groovy_lint".

### Actual Behavior

The supported source(s) is empty.

### Debug Log

empty

However, `nvim --clean -u minimal_init.lua Jenkinsfile.groovy` works. I also get this issue when running with `foobar.Jenkinsfile`.

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by mochaaP** [comment]
`Jenkinsfile`'s `filetype` should map to `groovy`: <https://github.com/neovim/neovim/blob/5db076c7ccfef6732516074252ac4b21b12fc629/runtime/lua/vim/filetype.lua#L1299>
