### ISSUE TITLE
Migrate selene checks to pre-commit

### ISSUE THREAD

**Issue by mochaaP** [nvimtools/none-ls.nvim#78]
selene-action is unmaintained and outdated, and since we already have pre-commit setup, we could migrate to the official pre-commit integration: <https://github.com/Kampfkarren/selene/pull/565>

**Comment by AlejandroSuero** [comment]
@mochaaP I have this action that I updated it to work with Node20. In case you want to give it a try.

- https://github.com/AlejandroSuero/selene-linter-action

**Comment by mochaaP** [comment]
partially done in `fef4bc70cdad8221cf6506090f437719bc393050`, waiting for it to land in a tagged release

**Comment by barrett-ruth** [comment]
I believe this is finished now?
