### ISSUE TITLE
Ruff is not showing up in auto generated builtin docs

### ISSUE THREAD

**Issue by joelmccoy** [nvimtools/none-ls.nvim#86]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

N/A

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Mac

### Minimal Config

```Lua
N/A
```

### Steps to Reproduce

There is no ruff documentation in the [BUILTINS.md ](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md) file even though there it appears to have been added [here](https://github.com/nvimtools/none-ls.nvim/pull/10).

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

I looked at [BUILTINS.md ](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md) to see if ruff was supported as a formatter, but I could not find any documentation.  A quick code search only brought up the PR in which it is added.   I think ruff should be added by the documentation generation script. 

### Actual Behavior

ruff does not appear in [BUILTINS.md ](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md)

### Debug Log

N/A

### Help

Yes

### Implementation Help

My assumption is that something is wrong with the doc generation [action](https://github.com/nvimtools/none-ls.nvim/blob/main/.github/workflows/docs.yml) and script which is causing ruff not to be added to this doc.  If someone can confirm this is the issue and has a suspicion as to why I would be willing to look into implementing a fix.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by mochaaP** [comment]
Ruff is removed in the favor of LSP / `none-ls-extras.nvim`.

See #81 and <https://github.com/nvimtools/none-ls-extras.nvim>.
