### ISSUE TITLE
bash-language-server → No code actions

### ISSUE THREAD

**Issue by Zeioth** [nvimtools/none-ls.nvim#89]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.9.5

### Dev Version?

- [x] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

arch

### Minimal Config

```Lua
x
```

### Steps to Reproduce

x

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

x

### Actual Behavior

x

### Debug Log

x

### Help

No

### Implementation Help

As indicated [here](https://github.com/nvimtools/none-ls.nvim/discussions/81) I've installed `shellcheck` on mason, as replacement for the built-in the `bash-language-server`.

What works:
* Linting       → Works ok: It requires you to install shellcheck.
* LSP           → Works ok: it requires you to install bash-language-server.
* Formatting → Works ok: it requires you to install shfmt.

What doesn't work:
* Code actions are not available anymore.

More info:
Previously I had code actions working with:

```
require("null-ls").builtins.code_actions.shellcheck
```

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by Zeioth** [comment]
Ok I've tested in a old version of none-ls and it seems this is a requirement for code actions to work:
```lua
require("null-ls").builtins.code_actions.shellcheck,
```
Because the built-in has been removed it seems there is no way to do this anymore.

**Comment by mochaaP** [comment]
If you are not against bash-language-server, you could make a PR to there. I mentioned the exact line of code somewhere in #81.

You could use [gbprod/none-ls-shellcheck.nvim](https://github.com/gbprod/none-ls-shellcheck.nvim) in the meantime.

**Comment by Zeioth** [comment]
Issue solved by adding this to none-ls config:

```lua
require("null-ls").register(require("none-ls-shellcheck.code_actions"))
```
but it requires the none-ls dependency "gbprod/none-ls-shellcheck.nvim".

It was documented. Sorry.

**Comment by Zeioth** [comment]
Maybe "gbprod/none-ls-shellcheck.nvim" should be shipped by default with none-ls and do `require("null-ls").register(require("none-ls-shellcheck.code_actions")) ` if shellcheck is loaded? 

Unless the fact linting still requires `shellcheck` to be installed is a bug. I have shellcheck installed. It doesn't appear listed on :LSPInfo but it works. If I uninstall shellcheck, linting stops working.
![screenshot_2024-03-06_16-06-44_180080521](https://github.com/nvimtools/none-ls.nvim/assets/3357792/7847a583-cea5-480c-b3fc-1c58600d99ba)

**Comment by mochaaP** [comment]
> Maybe `"gbprod/none-ls-shellcheck.nvim"` should be shipped by default with none-ls and do `require("null-ls").register(require("none-ls-shellcheck.code_actions")) ` if shellcheck is loaded?

This was intended and will not change.

**Comment by Zeioth** [comment]
As long as we add it to the wiki in the future it's cool.

**Comment by mochaaP** [comment]
> As long as we add it to the wiki in the future it's cool.

The wiki is open for everyone to edit. It's appreciated if you could do it!

**Comment by Zeioth** [comment]
I can't take care of the wiki atm sorry. But I will be helping with QA from [NormalNvim](https://github.com/NormalNvim/NormalNvim)

**Comment by Zeioth** [comment]
closing, as beautysh load correctly 

local beautysh = require("none-ls.formatting.beautysh") when the dependency "nvimtools/none-ls-extras.nvim" is present.

**Comment by Zeioth** [comment]
Re-opened, as this one seems to actually be a bug. 

It is currently necessary to do
```lua
"gbprod/none-ls-shellcheck.nvim"
      local nls = require("null-ls")
      local shellcheck_code_actions = require("none-ls-shellcheck.code_actions")
      nls.register(shellcheck_code_actions)  -- shell code actions.
```

in order to enable shell code actions. This shouldn't be necessary. According to [this](https://github.com/nvimtools/none-ls.nvim/discussions/81) bashls should include code actions already, which is not the case.

**Comment by mochaaP** [comment]
> If you are not against bash-language-server, you could make a PR to there. I mentioned the exact line of code somewhere in #81.

found it, <https://github.com/nvimtools/none-ls.nvim/discussions/81#discussioncomment-8583064> & <https://github.com/bash-lsp/bash-language-server/blob/afd0d82c5a0a3cbedef8098b8944d9b01c47657e/server/src/shellcheck/index.ts#L239>

**Comment by mochaaP** [comment]
cc @skovhus you might want to take a look at this. :)
