### ISSUE TITLE
none-ls.nvim doesn't integrate so seamlessly with mason-null-ls.nvim anymore

### ISSUE THREAD

**Issue by Zeioth** [nvimtools/none-ls.nvim#90]
### FAQ

- [X] I have checked the [FAQ](https://github.com/nvimtools/none-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.9.5

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

arch

### Minimal Config

```Lua
x
```

### Steps to Reproduce

x

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

x

### Actual Behavior

x

### Debug Log

x

### Help

No

### Implementation Help

Loading external builtins in the new way
```lua
require("null-ls").register(shellcheck_code_actions)
```

Suffices for end users, but it's not a good solution for distro maintainers. 

## Example
* I ship my distro with shellcheck.
* The final user decides to open mason and change his linter to a different one.

## Result
Both shellcheck and the new installed linter are going to appear as loaded in `:LspInfo`, as shellcheck is now hardcoded in the config (which was not previously necessary).

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by Zeioth** [comment]
There is no problem in requiring a dependency, but it shouldn't be necessary to hardcode loading clients in the config. It beats the point of none-ls.

**Comment by Zeioth** [comment]
I think showing in `:LspInfo` clients that can't be loaded (because they are not installed, they are just registered in the config) is a bug and it should probably not happen.

**Comment by Zeioth** [comment]
Also 
```lua
local nls = require("null-ls")
local luacheck = require("none-ls-luacheck.diagnostics.luacheck")
nls.register(luacheck)
```
Behaves in a weird way. If I remove the line:
```lua
nls.register(luacheck)
```
Linting still works, but it is not displayed on `:LspInfo`.

But if I have
```lua
nls.register(luacheck)
```
And I remove luacheck from mason, then `:LspInfo` will show it as loaded even if that's not true.

**Comment by Zeioth** [comment]
In the end we just migrated from luacheck to selene, and from beautysh to shfmt. While it's true these projects were stable and powerful, they are probably abandoned forever.

Feel free to close this issue if you consider it.

**Comment by mochaaP** [comment]
@jay-babu do you have time to take a look at this?

**Comment by citosid** [comment]
Do you have any update on this one? It is happening to me for 4 libraries:

![image](https://github.com/nvimtools/none-ls.nvim/assets/201430/94f03db9-0cce-4152-b9a8-021da071d094)

In my case I cannot migrate to `shfmt` since it is incompatible with some of our standards. 

Here is my configuration (using lazy.vim):

```lua
return {
	{
		"jay-babu/mason-null-ls.nvim",
		event = { "BufReadPre", "BufNewFile" },
		config = function()
			require("mason-null-ls").setup({
				-- Each of one of these needs to be added in the configuration for none-ls.nvim
				ensure_installed = {
					-- Diagnostics
					"beautysh",
					"eslint_d",
					"hadolint",
					"markdownlint", -- This is both, formatter and diagnostics

					-- Formatters
					"black",
					"isort",
					"jq",
					"prettier",
					"shellcheck",
					"stylua",
				},
			})
		end,
		lazy = true,
	},
	{
		"nvimtools/none-ls.nvim",
		dependencies = {
			"jay-babu/mason-null-ls.nvim",
		},
		event = { "BufReadPre", "BufNewFile" },
		lazy = true,
		opts = function(_, opts)
			local nls = require("null-ls")
			opts.sources = vim.list_extend(opts.sources or {}, {
				-- These come from the configuration for mason-null-ls.nvim

				-- Diagnostics
				nls.builtins.diagnostics.beautysh,
				nls.builtins.diagnostics.eslint_d,
				nls.builtins.diagnostics.hadolint,
				nls.builtins.diagnostics.markdownlint,

				-- Formatter
				nls.builtins.formatting.black,
				nls.builtins.formatting.isort,
				nls.builtins.formatting.jq,
				nls.builtins.formatting.markdownlint,
				nls.builtins.formatting.prettier,
				nls.builtins.formatting.shellcheck,
				nls.builtins.formatting.stylua,
			})

			opts.on_attach = function(current_client, bufnr)
				if current_client.supports_method("textDocument/formatting") then
					vim.api.nvim_clear_autocmds({ buffer = bufnr })
					vim.api.nvim_create_autocmd("BufWritePre", {
						buffer = bufnr,
						callback = function()
							vim.lsp.buf.format({
								filter = function(client)
									-- only use null-ls for formatting instead of lsp server
									return client.name == "null-ls"
								end,
								bufnr = bufnr,
							})
						end,
					})
				end
			end
		end,
	},
}

```

**Comment by Zeioth** [comment]
See also: https://github.com/nvimtools/none-ls.nvim/issues/122#issuecomment-2104930403

**Comment by Zeioth** [comment]
I was thinking a possible solution would be not attaching the `source` if the `command` is not available on the terminal. I'm gonna see if I can pull it off during the weekend.

**Comment by Zeioth** [comment]
I already got a local solution working:

```lua
  --  none-ls [lsp code formatting]
  --  https://github.com/nvimtools/none-ls.nvim
  {
    "nvimtools/none-ls.nvim",
    dependencies = {
      "jay-babu/mason-null-ls.nvim",
      "nvimtools/none-ls-extras.nvim",
    },
    event = "VeryLazy",
    opts = function()

      -- fix: Register the extra builtin reformat_gherkin only if the command is available.
      local reformat_gherkin = require("none-ls.formatting.reformat_gherkin")
      local cmd = reformat_gherkin._opts.command
      if vim.fn.executable(cmd) == 1 then
        require("null-ls.sources").register(reformat_gherkin)
      end

      return {} -- opts are not necessary for this example
    end
  },
```
This code will only try to load the extra builtin if its command is executable.

I don't know if I can implement this login into none-ls itself so the user doesn't have to use hacks such as this. I'm gonna try.

**Comment by Zeioth** [comment]
Issue located in null-ls-mason not having added support for external sources yet. Closing and moving the issue to https://github.com/nvimtools/none-ls.nvim/issues/125
